package com.hzq.initer.compiler;

/**
 * Created by hezhiqiang on 2018/11/26.
 */

public class Consts {
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "Initer";
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler";
    public static final String ANNOTATION_NAME = "com.hzq.initer.annotation.Inite";
    public static final String KEY_MODULE_NAME = "moduleName";
    public static final String TEMPLATE_NAME = "com.hzq.initer.api.IComponentInit";
    public static final String GENERATE_CLASS_NAME = "_InitImpl";
    public static final String CONTEXT_NAME = "android.content.Context";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.hzq.initer.auto"; //generator class package name
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY LCS_PROCESSOR.";
}
